[pytest]
addopts = -s -v --headed
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Маркировка для smoke-тестов
    regression: Маркировка для регрессионных тестов
    prod: Маркировка для тестов на prod-окружение
    dev: Маркировка для тестов на dev-окружение
    inventory: Inventory tests
